#!/bin/bash

PRODUCT_NAME=Notion
RESOURCE_DIR=build/resources-$NOTION_VERSION
BUILD_DIR=build/build-$NOTION_VERSION-$PACKAGE_REVISION-$BUILD_ARCH
BUILD_DIR_ENHANCED=build/build-enhanced-$NOTION_VERSION-$PACKAGE_REVISION-$BUILD_ARCH
PATH="node_modules/.bin:$PATH"

if [[ "$APP_NAME" == notion-enhanced ]]; then
  BUILD_DIR=$BUILD_DIR_ENHANCED
  PRODUCT_NAME='Notion Enhanced'
fi

export PRODUCT_NAME RESOURCE_DIR BUILD_DIR BUILD_DIR_ENHANCED PATH
