#!/bin/bash

APP_NAME=notion-desktop
ELECTRON_VERSION=11.2.2
NOTION_VERSION=2.0.11
PACKAGE_REVISION=5
BUILD_ARCH=x64
PACKAGE_ARCH=$1

export APP_NAME ELECTRON_VERSION NOTION_VERSION PACKAGE_REVISION BUILD_ARCH PACKAGE_ARCH
